# Generated by Django 4.0.5 on 2022-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_testmodel_description_remove_testmodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='category',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='subcatgeory',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
